### ISSUE TITLE
MVP

### ISSUE THREAD

**Issue by xynree** [znschaffer/rating-room#37]
- [ ] RR has 100+ products
- [ ] All products have description and 1+ tags
- [ ] All products have reviews from both @xynree  and @zschaffer 
- [x] Codebase is setup with Typescript #33 
- [x] Filtering, Sorting, and Search functionality finalized #31 #32
- [x] Schema finalized
- [x] Unit Testing for all pure functions #23 
- [x] Layout working on Mobile #7 
- [x]  Favicon Added #24 
- [ ] Deployed
